version: '3.9'

services:
  php-app:
    build:
      context: .
      dockerfile: php.Dockerfile
    image: dating-dev-env
    container_name: app
    restart: unless-stopped
    volumes:
     - ./:/var/www 
  
  nginx:
      build:
        context: .
        dockerfile: nginx.dev.Dockerfile
      image: nginx
      container_name: nginx
      restart: unless-stopped
      ports:
        - "3000:80"
      volumes:
        - ./:/var/www
        - ./nginx/:/etc/nginx/conf.d/
      depends_on:
        - php-app
  
  db:
    platform: linux/x86_64
    image: mysql:5.7.37
    container_name: db
    restart: unless-stopped
    ports:
     - 3306:3306
    volumes:
      - ./resources/sql/Sample_2022.sql:/docker-entrypoint-initdb.d/Sample_2022.sql
    environment:
      MYSQL_DATABASE: dating_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: password 

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped 
    ports:
      - 8080:80
    environment:
       PMA_ARBITRARY: 1
       PMA_HOST: db
       PMA_USER: root
       PMA_PASSWORD: secret

